name: Create Release

on:
  push:
    tags:
      - 'v*' # Trigger on version tags

jobs:
  create_release:
    name: Create Release
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: gfastats ${{ github.ref }}
        body: |
          Changes in this Release
        draft: false
        prerelease: false
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}

  add_resources:
    needs: create_release
    name: Add Resources
    strategy:
      matrix:
        OS: [macos-13, ubuntu-latest, windows-2019]
        include:
        - OS: macos-13
          OS_NAME: macOS
        - OS: ubuntu-latest
          OS_NAME: linux
        - OS: windows-latest
          OS_NAME: win
    runs-on: ${{ matrix.OS }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
            submodules: recursive
      - name: Build
        run: make -j
        
      - name: Make binary executable (Linux & macOS)
        if: matrix.OS_NAME != 'win'
        run: chmod +x build/bin/gfastats

      - name: Zip (Windows)
        if: matrix.OS_NAME == 'win'
        uses: papeloto/action-zip@v1
        with:
          files: build/bin/gfastats.exe
          dest: result.zip

      - name: Tar (Linux & macOS)
        if: matrix.OS_NAME != 'win'
        run: tar -czvf result.tar.gz -C build/bin gfastats

      - name: Add binaries & Upload tarball (Linux & macOS)
        if: matrix.OS_NAME != 'win'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: result.tar.gz
          asset_name: gfastats.${{ github.ref_name }}-${{matrix.OS_NAME}}.tar.gz
          asset_content_type: application/tar
          
      - name: Add binaries & Upload tarball (Windows)
        if: matrix.OS_NAME == 'win'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: result.zip
          asset_name: gfastats.${{ github.ref_name }}-${{matrix.OS_NAME}}.zip
          asset_content_type: application/zip

  add_submodules:
    needs: create_release
    name: Source with submodules
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
            submodules: true
      - name: Zip
        uses: papeloto/action-zip@v1
        with:
          files: .
          dest: result.zip
      - name: Add files
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: result.zip
          asset_name: gfastats.${{ github.ref_name }}-with_submodules.zip
          asset_content_type: application/zip
